characters = [
	//fnaf
	"Freddy.png",
	"Bonnie.png",
	"Chica.png",
	"Foxy.png",
	"Phone Guy.png",
	//fnaf2
	"Toy Freddy.png",
	"Toy Bonnie.png",
	"Toy Chica.png",
	"Mangle.png",
	"Balloon Boy.png",
	"JJ.png",
	"The Puppet.png",
	"Withered Bonnie.png",
	"Withered Chica.png",
	"Withered Golden Freddy.png",
	"RWQFSFASXC.png",
	//fnaf3
	"Springtrap.png",
	"Phantom Freddy.png",
	"Phantom BB.png",
	"Phantom Mangle.png",
	//fnaf4
	"Nightmare Freddy.png",
	"Nightmare Bonnie.png",
	"Nightmare Chica.png",
	"Nightmare Fredbear.png",
	"Plushtrap.png",
	"Nightmare.png",
	"Freddles.png",
	"Jack-O-Chica.png",
	"Nightmare Mangle.png",
	"Nightmare BB.png",
	"Nightmarionne.png",
	//fw
	"Adventure Endo01.png",
	"Dee Dee.png",
	"Old Man Consequences.png",
	//sl
	"Circus Baby.png",
	"Ballora.png",
	"Funtime Foxy.png",
	"Minireenas.png",
	"Ennard.png",
	"Lolbit.png",
	"Bonnet.png",
	//ffps
	"Molten Freddy.png",
	"Afton.png",
	"Scrap Baby.png",
	"Lefty.png",
	"Helpy.png",
	"Bucket Bob.png",
	"No. 1 Crate.png",
	"Mr. Can-Do.png",
	"Happy Frog.png",
	"Mr. Hippo.png",
	"Pigpatch.png",
	"Nedd Bear.png",
	"Rockstar Freddy.png",
	"Rockstar Bonnie.png",
	"Rockstar Chica.png",
	"Rockstar Foxy.png",
	"Orville Elephant.png",
	"El Chip.png",
	"Funtime Chica.png",
	"Music Man.png",
	"Candy Cadet.png",
	//ucn
	"Fredbear.png",
]