characters = [
	//fnaf
	"Freddy.png",
	"Bonnie.png",
	"Chica.png",
	"Foxy.png",
	"Golden Freddy.png",
	"Endo01.png",
	"Mr. Cupcake.png",
	"Phone Guy.png",
	//fnaf2
	"Toy Freddy.png",
	"Toy Bonnie.png",
	"Toy Chica.png",
	"Mangle.png",
	"Balloon Boy.png",
	"JJ.png",
	"The Puppet.png",
	"Withered Freddy.png",
	"Withered Bonnie.png",
	"Withered Chica.png",
	"Withered Foxy.png",
	"Withered Golden Freddy.png",
	"Shadow Freddy.png",
	"RWQFSFASXC.png",
	"Endo02.png",
	"Paperpals.png",
	//fnaf3
	"Springtrap.png",
	"Phantom Freddy.png",
	"Phantom Chica.png",
	"Phantom BB.png",
	"Phantom Foxy.png",
	"Phantom Mangle.png",
	"Phantom Puppet.png",
	//fnaf4
	"Nightmare Freddy.png",
	"Nightmare Bonnie.png",
	"Nightmare Chica.png",
	"Nightmare Foxy.png",
	"Nightmare Fredbear.png",
	"Plushtrap.png",
	"Nightmare.png",
	"Freddles.png",
	"Jack-O-Bonnie.png",
	"Jack-O-Chica.png",
	"Nightmare Mangle.png",
	"Nightmare BB.png",
	"Nightmarionne.png",
	//fw
	"Adventure Endo01.png",
	"Dee Dee.png",
	"Old Man Consequences.png",
	//sl
	"Circus Baby.png",
	"Ballora.png",
	"Funtime Freddy.png",
	"Funtime Foxy.png",
	"Ennard.png",
	"Bidybab.png",
	"Minireenas.png",
	"Lolbit.png",
	"Yenndo.png",
	"Bon-Bon.png",
	"Bonnet.png",
	"Electrobab.png",
	"HandUnit.png",
	"Little Joe.png",
	"Magician Toy.png",
	"Dark Springtrap.png",
	//ffps
	"Molten Freddy.png",
	"Afton.png",
	"Scrap Baby.png",
	"Lefty.png",
	"Helpy.png",
	"Bucket Bob.png",
	"Mr. Hugs.png",
	"No. 1 Crate.png",
	"Mr. Can-Do.png",
	"Pan Stan.png",
	"Happy Frog.png",
	"Mr. Hippo.png",
	"Pigpatch.png",
	"Nedd Bear.png",
	"Orville Elephant.png",
	"Rockstar Freddy.png",
	"Rockstar Bonnie.png",
	"Rockstar Chica.png",
	"Rockstar Foxy.png",
	"El Chip.png",
	"Funtime Chica.png",
	"Music Man.png",
	"Candy Cadet.png",
	"Prize King.png",
	//ucn
	"Fredbear.png",
	"XOR.png",
	//hw
	"Glitchtrap.png",
	"Dreadbear.png",
	"Grimm Foxy.png",
	//ar
	"Freddy Frostbear.png",
	"8-Bit Baby.png",
	//sb
	"Glamrock Freddy.png",
	"Montgomery Gator.png",
	"Glamrock Chica.png",
	"Roxanne Wolf.png",
	"Sun.png",
	"Moon.png",
	"Mini Music Man.png",
	"DJ Music Man.png",
	"Security Bot.png",
	"Caution Bot.png",
	"Glamrock Endo.png",
	"Gregory.png",
	"Vanny.png",
	"Burntrap.png",
	"The Blob.png",
	//ruin
	"The Mimic.png",
	"MXES.png",
	"Helpi.png",
	"Glamrock Bonnie.png",
	//hw2
	"Mystic Hippo.png",
	//sotm
	"Mr. Helpful.png",
	"Mrs. Helpful.png",
	"Jackie.png",
	"Digi-Typer.png",
	"Big Top.png",
	"Captain.png",
	"Dollie.png",
	"Party Time Chica.png",
	"Bub.png",
	"White Tiger.png",
	"Sleepy Moon.png",
]